---
- hosts: all
  become: no
  tasks:
          - name: Add the user 'ansible' with a specific uid and a primary group of 'admin'
            user:
              name: ansible
              comment: ansible user
              uid: 1040
              group: admin
              generate_ssh_key: yes
              ssh_key_bits: 2048
              ssh_key_file: .ssh/id_rsa
